# Site settings
title:       Tragédia do Rio Doce
email:       mab@mabnacional.org.br
author:      MAB - Movimento dos Atingidos por Barragens
description: ""
baseurl:     "http://guilhermeweimann1.github.io/tragediariodoce/"


# Google analytics
google_analytics: xxx

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Social icons
show_social_icons: true
github_username:
twitter_username: MAB_Brasil
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
permalink:    pretty
asset_pipeline:
  gzip: true
sass:
  style: compressed
timezone: BR
gems:
  - jekyll-sitemap
exclude:
  - deploy
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - README.md
  - bower_components
  - node_modules
  - package.json
  - assets/less
  - test
  - Rakefile
  - job_status.txt
  - setup
  - vendor
  - node/