# Site settings
title:       Tragédia Anunciada
name:        Tragédia Anunciada
email:       mab@mabnacional.org.br
mab_url:     http://www.mabnacional.org.br/
author:      MAB - Movimento dos Atingidos por Barragens
description: "Tragédia anunciada: o que garante os direitos é o povo organizado!"
short_description: O crime do Rio Doce jamais será esquecido 
baseurl:
url:         http://tragedianunciada.mabnacional.org.br

# Google analytics
google_analytics: UA-71968545-1

facebook: 939381472775553

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Social icons
show_social_icons: true
github_username:
twitter_username: MAB_Brasil
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
permalink:    pretty
#paginate: 6
#paginate_path: "/noticias/:num/"
asset_pipeline:
  gzip: true
sass:
  style: compressed
timezone: BR
gems:
  - jekyll-sitemap
exclude:
  - deploy
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - README.md
  - bower_components
  - node_modules
  - package.json
  - assets/less
  - test
  - Rakefile
  - job_status.txt
  - setup
  - vendor
  - node/
